name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Prepare Folders
        run: |
          mkdir -p www
          cp index.html www/
      - name: Install Tools
        run: |
          npm install @capacitor/cli @capacitor/core @capacitor/android
          npx cap init "MyGame" "com.myname.game" --web-dir www
          npx cap add android
      - name: Build APK
        run: |
          npx cap copy android
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug -Dorg.gradle.java.home=$JAVA_HOME_17_X64
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
